version: '3.9'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    #volumes:
    #  - ./langgraph_workflow.py:/app/langgraph_workflow.py
    environment:
      - HF_API_KEY=${HF_API_KEY}

  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
